### ISSUE TITLE
Normalize network in docker-compose.yaml

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-python-demo#85]
Most demonstrations will use an existing docker-network.   To allow individual docker-compose.yaml files to work together,  the common format is:

```yaml
networks:
  senzing:
    external: true
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}
```
### References:

- https://docs.docker.com/compose/compose-file/#external
- https://docs.docker.com/compose/compose-file/#name
